---
title: "Mechanism Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(caret)
library(tidymodels)
```

Read in clean data
```{r}
model_df_final_detect = read_rds("data_to_model/model_df_final_detect.rds")
model_df_final_count = read_rds("data_to_model/model_df_final_count.rds")

```


```{r}
#new_data_to_model_detect 
```


Do train and test split on the old data 
Set up resampling (10 fold cross validation)
Drop unused columns
Stratify the random sample by the outcome

```{r}
cols_not_mod = c("cpsc_case_number","psu","stratum","weight","treatment_date")
    
init_split <- initial_split(model_df_final_detect, prop = .75, strata = "primary_mechanism")

train_df_detect <- training(init_split)
test_df_detect <- testing(init_split)

train_df_count <- model_df_final_count[init_split$in_id,]
test_df_count <- model_df_final_count[-init_split$in_id,]

trctrl <- trainControl(method = "cv", number = 10, verboseIter = T)
select(train_df_detect, -all_of(cols_not_mod) )
select(train_df_count, -all_of(cols_not_mod) )
```


Run the model and review confusion matrix
```{r}
lin_mod_detect <- train(primary_mechanism~., data = select(train_df_detect, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl)
lin_mod_count <- train(primary_mechanism~., data = select(train_df_count, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl)

```


Accounting for survey weights
```{r}
lin_mod_detect_wt <- train(primary_mechanism~., data = select(train_df_detect, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl, weights = train_df_detect$weight)
lin_mod_count_wt <- train(primary_mechanism~., data = select(train_df_count, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl, weights = train_df_detect$weight)

```

Saving models to an RDS file
```{r}

train_df_detect |> write_rds("Model Objects/train_df_detect.RDS")
test_df_detect |> write_rds("Model Objects/test_df_detect.RDS")

train_df_count |> write_rds("Model Objects/test_df_count.RDS")
test_df_count |> write_rds("Model Objects/test_df_count.RDS")


lin_mod_detect |> write_rds("Model Objects/lin_mod_detect.RDS")
lin_mod_detect_wt |> write_rds("Model Objects/lin_mod_detect_wt.RDS")

lin_mod_count |> write_rds("Model Objects/lin_mod_count.RDS")
lin_mod_count_wt |> write_rds("Model Objects/lin_mod_count_wt.RDS")

```


