---
title: "Mechanism Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(caret)
library(tidymodels)
```

Read in models & data
```{r}
lin_mod_detect = read_rds("../Model Objects/lin_mod_detect.RDS")
lin_mod_detect_wt = read_rds("../Model Objects/lin_mod_detect_wt.RDS")

lin_mod_count = read_rds("../Model Objects/lin_mod_count.RDS")
lin_mod_count_wt = read_rds("../Model Objects/lin_mod_count_wt.RDS")


#train_df_detect = read_rds("Model Objects/train_df_detect.RDS")
test_df_detect = read_rds("../Model Objects/test_df_detect.RDS")

#train_df_count = read_rds("Model Objects/test_df_count.RDS")
test_df_count = read_rds("../Model Objects/test_df_count.RDS")

new_data_to_model_detect = read_rds("../data_to_model/new_data_to_model_detect.RDS")
new_data_to_model_count = read_rds("../data_to_model/new_data_to_model_count.RDS")
```


Create confusion matrix for unweighted result
```{r}
lin_preds_detect <- predict(lin_mod_detect, test_df_detect)
lin_preds_count <- predict(lin_mod_count, test_df_count)

confusionMatrix(lin_preds_detect, test_df_detect$primary_mechanism)
confusionMatrix(lin_preds_count, test_df_count$primary_mechanism)

```



Apply unweighted model predictions on new 2020-2022 data
```{r}
new_lin_preds_detect <- predict(lin_mod_detect, new_data_to_model_detect)
new_lin_preds_count <- predict(lin_mod_count, new_data_to_model_count)

table(new_lin_preds_detect)
table(new_lin_preds_count)

indxs = which(new_lin_preds_detect != new_lin_preds_count)

new_data_to_model_detect_wprerds = new_data_to_model_detect |> mutate(detect_pred = new_lin_preds_detect , count_pred = new_lin_preds_count)

narr_tbl = read_csv("../data_to_model/narrative_tbl_all.csv")

new_data_to_model_detect_wprerds[indxs,] |> left_join(narr_tbl) |> write_csv("../disagree_rows.csv")
```


Accounting for survey weights
```{r}
lin_preds_detect_wt <- predict(lin_mod_detect_wt, test_df_detect)
lin_preds_count_wt <- predict(lin_mod_count_wt, test_df_count)

confusionMatrix(lin_preds_detect_wt, test_df_detect$primary_mechanism)
confusionMatrix(lin_preds_count_wt, test_df_count$primary_mechanism)
```


Review elbow charts by model type
```{r}
plot(lin_mod_detect)
plot(lin_mod_detect_wt)
plot(lin_mod_count)
plot(lin_mod_count_wt)
```


Variable Importance values
```{r}
varImp(lin_mod_detect)
varImp(lin_mod_detect_wt)
```


