---
title: "Mechanism Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(caret)
library(tidymodels)
library(survey)
```


```{r}
train_df_count = read_csv("../data_to_model/Train and Test Sets/train_df_count.csv")
test_df_count = read_csv("../data_to_model/Train and Test Sets/test_df_count.csv")

train_df_detect = read_csv("../data_to_model/Train and Test Sets/train_df_detect.csv")
test_df_detect = read_csv("../data_to_model/Train and Test Sets/test_df_detect.csv")
```



```{r}
cols_not_mod = c("cpsc_case_number","psu","stratum","weight","treatment_date")
trctrl <- trainControl(method = "cv", number = 10, verboseIter = T)
#select(train_df_detect, -all_of(cols_not_mod) )
#select(train_df_count, -all_of(cols_not_mod) )
```


Train the models unweighted
```{r}
lin_mod_detect <- train(primary_mechanism~., data = select(train_df_detect, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl)
lin_mod_count <- train(primary_mechanism~., data = select(train_df_count, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl)

```


Accounting for survey weights
```{r}
lin_mod_detect_wt <- train(primary_mechanism~., data = select(train_df_detect, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl, weights = train_df_detect$weight)
lin_mod_count_wt <- train(primary_mechanism~., data = select(train_df_count, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl, weights = train_df_detect$weight)
lin_mod_count_bin_wt <- train(primary_mechanism_bin~., data = select(train_df_count_bin, -all_of(cols_not_mod) ), method = "xgbLinear", trControl = trctrl, weights = train_df_count_bin$weight)
```



Saving models, train+test sets to RDS files
```{r}

train_df_detect |> write_rds("../Model Objects/train_df_detect.RDS")
test_df_detect |> write_rds("../Model Objects/test_df_detect.RDS")

train_df_count |> write_rds("../Model Objects/test_df_count.RDS")
test_df_count |> write_rds("../Model Objects/test_df_count.RDS")

train_df_count_bin |> write_rds("../Model Objects/train_df_count_bin.RDS")
test_df_count_bin |> write_rds("../Model Objects/test_df_count_bin.RDS")


lin_mod_detect |> write_rds("../Model Objects/lin_mod_detect.RDS")
lin_mod_detect_wt |> write_rds("../Model Objects/lin_mod_detect_wt.RDS")

lin_mod_count |> write_rds("../Model Objects/lin_mod_count.RDS")
lin_mod_count_wt |> write_rds("../Model Objects/lin_mod_count_wt.RDS")


lin_mod_count_bin |> write_rds("../Model Objects/lin_mod_count_bin.RDS")
lin_mod_count_bin_wt |> write_rds("../Model Objects/lin_mod_count_bin_wt.RDS")

```